version: "3.9"
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MGUSER}
      - MONGO_INITDB_ROOT_PASSWORD=${MGPASSWORD}
    ports:
      - ${MGPORT}:${MGPORT}
    volumes:
      - ./data:/data/db